version: "3.9"

networks:
  app-tier:
    driver: bridge

services:
  nginx:
   build: .
   depends_on:
      - phpfpm
   networks:
      - app-tier
   ports:
    - "80:80"
    - "443:443"
  #  volumes:
  #   - "$PWD/conf/nginx.conf:/etc/nginx/nginx.conf"
  phpfpm:
    image: 'bitnami/php-fpm:latest'
    networks:
      - app-tier
